version: "3.8"

services:
  web:
    build: ./flask-app
    ports:
      - "5000:5000"
    env_file:
      - .env.dev
    volumes:
      - ./flask-app:/app
    working_dir: /app
    command: flask run --host=0.0.0.0
