services:
  flask-app:
    build:
      context: ./flask-app
    container_name: hoa-flask
    ports:
      - "5000:5000"
    volumes:
      - ./flask-app:/app
    working_dir: /app
    command: python run.py
    restart: unless-stopped
